version: "1.0"

services:

  db:
    image: postgres:14
    container_name: db
    networks:
      - my_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mai_master_degree_systems_analysis
      #- POSTGRES_INITDB_ARGS='--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  backend-python-fastapi-fastapi:
    build:
      context: ./backend-python-fastapi
    container_name: backend-python-fastapi
    networks:
      - my_network
    ports:
      - 8092:8092
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/mai_master_degree_systems_analysis
  
  
  

networks:
  my_network:
volumes:
  postgres-data: