"""Init0

Revision ID: c69596120de1
Revises: 
Create Date: 2024-10-31 02:31:49.268799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69596120de1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('auth_key', sa.String(length=32), nullable=True),
    sa.Column('access_token', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False, default=1, server_default="1"),
    sa.Column('lastname', sa.String(length=256), nullable=True),
    sa.Column('firstname', sa.String(length=256), nullable=True),
    sa.Column('date_of_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=36), nullable=True),
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('text_message', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Integer(), nullable=False, default=0, server_default="0"),
    sa.Column('date_of_add', sa.DateTime(), nullable=True),
    sa.Column('date_of_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=True)
    op.create_table('email_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('date_of_add', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_folder_id'), 'email_folder', ['id'], unique=True)
    op.create_table('connection_email_to_email_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_folder_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('date_of_add', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_folder_id'], ['email_folder.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_email_to_email_folder_id'), 'connection_email_to_email_folder', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_email_to_email_folder_id'), table_name='connection_email_to_email_folder')
    op.drop_table('connection_email_to_email_folder')
    op.drop_index(op.f('ix_email_folder_id'), table_name='email_folder')
    op.drop_table('email_folder')
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
